//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LDFProcess.rc
//
#define ID_APPLY_LEGEND                 3
#define ID_Btn_ZOOMIN                   5
#define ID_Btn_ZOOMOUT                  6
#define ID_Btn_SAVE                     7
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LDFPROCESS_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_INPUT                129
#define IDD_DIALOG_OUTPUT               130
#define IDD_DIALOG_clouddetection       131
#define IDD_DIALOG_CALCULATE            132
#define IDD_DIALOG_LEGEND               133
#define IDD_DIALOG_abnormalmodel        134
#define IDC_BUT_SEL                     1000
#define IDC_BUTTON3                     1001
#define IDC_BUT_Extend                  1001
#define IDC_EDIT1                       1002
#define IDC_BUT_Output                  1002
#define IDC_BUT_Add                     1002
#define IDC_EDIT_OUTPUT                 1002
#define IDC_EDIT_MINVALUE               1002
#define IDC_EDIT8                       1003
#define IDC_BUTTON1                     1003
#define IDC_EDIT_INPUT                  1003
#define IDC_EDIT_MONTH2                 1003
#define IDC_EDIT_OUTPUT2                1003
#define IDC_EDIT_SELBKGND               1003
#define IDC_EDIT_BKGND                  1003
#define IDC_BUT_Legend                  1003
#define IDC_EDIT_MAXVALUE               1003
#define IDC_RADIO1                      1004
#define IDC_EDIT9                       1004
#define IDC_BUT_Browser                 1004
#define IDC_BUT_Del                     1004
#define IDC_EDIT_MONTH3                 1004
#define IDC_RADIO_KValue                1004
#define IDC_RADIO_background            1004
#define IDC_EDIT_KMINVALUE              1004
#define IDC_RADIO2                      1005
#define IDC_EDIT10                      1005
#define IDC_BUT_Abnormal                1005
#define IDC_BUT_Clear                   1005
#define IDC_EDIT_MONTH4                 1005
#define IDC_RADIO_RST                   1005
#define IDC_RADIO_abnormaldetection     1005
#define IDC_EDIT_MAXVALUE2              1005
#define IDC_EDIT_KMAXVALUE              1005
#define IDC_RADIO3                      1006
#define IDC_EDIT2                       1006
#define IDC_EDIT_MONTH5                 1006
#define IDC_RADIO_Wavelet               1006
#define IDC_BUT_CAL                     1006
#define IDC_RADIO_together              1006
#define IDC_EDIT_FONTSIZE_LON_LAT       1006
#define IDC_EDIT3                       1007
#define IDC_CHECK1                      1007
#define IDC_EDIT_MONTH6                 1007
#define IDC_CHEK_Pseudocolor            1007
#define IDC_CHECK_epicenter             1007
#define IDC_EDIT4                       1008
#define IDC_CHECK2                      1008
#define IDC_BUT_Input                   1008
#define IDC_EDIT_MONTH7                 1008
#define IDC_CHEK_Kpseudocolor           1008
#define IDC_CHECK_provin_border         1008
#define IDC_EDIT11                      1009
#define IDC_CHECK3                      1009
#define IDC_EDIT5                       1009
#define IDC_BUT_CLOUDetection           1009
#define IDC_EDIT_BUTTOM                 1009
#define IDC_EDIT_BOTTOM                 1009
#define IDC_EDIT_MONTH8                 1009
#define IDC_CHEK_Statistics             1009
#define IDC_CHECK_fault                 1009
#define IDC_CHECK_FAault                1009
#define IDC_EDIT12                      1010
#define IDC_EDIT6                       1010
#define IDC_EDIT_TOP                    1010
#define IDC_EDIT_MONTH9                 1010
#define IDC_CHEK_Pseudocolor2           1010
#define IDC_CHEK_Clddetection2          1010
#define IDC_EDIT_StatisticArea          1010
#define IDC_EDIT_AddStatisticArea       1010
#define IDC_EDIT13                      1011
#define IDC_EDIT7                       1011
#define IDC_EDIT_LATRES                 1011
#define IDC_EDIT_MONTH10                1011
#define IDC_RADIO4                      1011
#define IDC_RADIO_split                 1011
#define IDC_EDIT_SIZE_provinborder      1011
#define IDC_EDIT14                      1012
#define IDC_RADIO_Folder                1012
#define IDC_EDIT_MONTH11                1012
#define IDC_EDIT_SIZE_epicenter         1012
#define IDC_EDIT15                      1013
#define IDC_RADIO_Files                 1013
#define IDC_EDIT_MONTH12                1013
#define IDC_CHEK_Statistics2            1013
#define IDC_CHEK_Compound               1013
#define IDC_EDIT_SIZE_fault             1013
#define IDC_LIST1                       1015
#define IDC_LIST_FILE                   1015
#define IDC_LIST_StatisticArea          1015
#define IDC_STATIC_COUNT                1016
#define IDC_EDIT_LEFT                   1017
#define IDC_EDIT_RIGHT                  1018
#define IDC_EDIT_LONRES                 1019
#define IDC_EDIT_MONTH1                 1020
#define IDC_SEPARATOR                   1022
#define IDC_BUT_OUTSEL                  1024
#define IDC_PROGRESS                    1025
#define IDC_BUT_OUTSEL2                 1025
#define IDC_BUT_SELBKGND                1025
#define shux                            1026
#define IDC_STATIC_INPUT                1027
#define IDC_STATIC_TIME                 1028
#define IDC_STATIC_PERCENT              1029
#define IDC_LIST_FILE_LEGEND            1030
#define IDC_PIC_SHOW                    1031
#define IDC_PIC_LEGEND                  1032
#define IDC_COMBO_Channel               1034
#define IDC_COMBO_SelChannel            1034
#define IDC_BUTTON2                     1035
#define IDC_ClrBtn_epicenter            1035
#define IDC_ClrBtn_epicenter2           1036
#define IDC_ClrBtn_provinborder         1036
#define IDC_ClrBtn_epicenter3           1037
#define IDC_ClrBtn_fault                1037
#define IDC_RADIO_circle                1038
#define IDC_RADIO_rectangle             1039
#define IDC_ClrBtn_StatisticArea        1040
#define IDC_SLIDER1                     1041
#define IDC_SLIDER_StatisticArea        1041
#define IDC_SLIDER_Trans_StatisticArea  1041
#define IDC_STATIC_                     1042
#define IDC_STATIC_StatisticArea_ColorTrans 1042
#define IDC_STATIC_StatisticArea_ColorTrans2 1043
#define IDC_STATIC_StatisticArea_ColorTrans3 1044
#define IDC_RADIO_rectangle2            1045
#define IDC_RADIO_fault                 1045

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
